# config.yaml

path: ./
data_path: ../HAICon2021_dataset
processed_dataset_path: ./processed_dataset
checkpoint_path: ./checkpoints
output_path: ./result
save_path: ./save
workers: 4
seed: 72


# data parameters
window_given: 89
window_size: 90
stride: 10
loader_params:
  batch_size: 512
  shuffle: True
  num_workers: 4
  pin_memory: True


# Train parameters
epochs: 30
early_patience: 10
early_verbose: False

# model parameters
StackedGRU:
  n_hidden: 100
  n_layers: 3


LSTMAE:


1DCONVAE:


TAnoGAN:


MADGAN:


GPT:
  hidden_size: 128
  n_layer: 3
  n_head: 1
  n_inner: 4*128
  activation_function: relu
  n_positions: 1024
  resid_pdrop: 0.1
  attn_pdrop: 0.1
