# config.yaml

path: ./
data_path: ../HAICon2021_dataset
processed_dataset_path: ./processed_dataset
checkpoint_path: ./checkpoints
output_path: ./result
save_path: ./save
workers: 4
seed: 72


# data parameters
window_given: &window_given 89
window_size: 90
stride: 10
loader_params:
  batch_size: 512
  shuffle: True
  num_workers: 4
  pin_memory: True


# Train parameters
epochs: 30
early_patience: 10
early_verbose: False


# model parameters
GRU:
  n_hidden: 100
  n_layers: 3


LSTMAE:
  seq_len: *window_given


CONV1dAE:
  kernel_size: 7
  stride: 2
  padding: 3


TransformerEncoder:
  num_heads: 1
  seq_len: *window_given
  ff_dim: 4
  num_transformer_blocks: 4
  mlp_units:
    - 86
    - 86
  mlp_dropout: 0.4
  dropout: 0.25

GPT:
  hidden_size: 128
  max_len: *window_given
  n_layer: 3
  n_head: 1
  n_inner: 512
  activation_function: relu
  n_positions: 1024
  resid_pdrop: 0.1
  attn_pdrop: 0.1
