# config.yaml

path: ./
data_path: ../HAICon2021_dataset
processed_dataset_path: ./processed_dataset
output_path: ./result
save_path: ./save
workers: 4
seed: 72

# result email
senderAddr: hwk0702@gmail.com
recipientAddr: hwk0702@gmail.com
password: fjwfqwjalwvnqagf

# data parameters
window_given: 89
window_size: 90
stride: 10
loader_params:
  batch_size: 512
  shuffle: True
  num_workers: 4
  pin_memory: True


# model parameters
StackedGRU:
  n_hidden: 100
  n_layers: 3

AE:

VAE: